version: '3.7'
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.5.0
    volumes:
      - "./filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro"
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./logs:/logs:rw"
    networks:
      - elastic

  logstash:
    image: docker.elastic.co/logstash/logstash:7.5.0
    volumes:
      - "./logstash-pipeline/:/usr/share/logstash/pipeline/:ro"
      - "./logstash-settings/:/usr/share/logstash/config/:ro"
      - "./logstash-patterns/:/usr/share/logstash/patterns/:ro"
      - "./logstash-templates/:/usr/share/logstash/templates/:ro"
    ports:
      - 5044:5044
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    environment:
      SERVER_NAME: kibana.test
      ELASTICSEARCH_HOSTS: http://es01:9200
    ports:
      - 80:5601
    networks:
      - elastic
    #volumes:
    #  - ./kibana.yml:/usr/share/kibana/config/kibana.yml

  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: es01
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es02,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
  es02:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: es02
    environment:
      - node.name=es02
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es03
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data02:/usr/share/elasticsearch/data
    networks:
      - elastic
  es03:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: es03
    environment:
      - node.name=es03
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01,es02
      - cluster.initial_master_nodes=es01,es02,es03
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data03:/usr/share/elasticsearch/data
    networks:
      - elastic

volumes:
  data01:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/carneirofc/logstash/data01"
  data02:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/carneirofc/logstash/data02"
  data03:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "/home/carneirofc/logstash/data03"

networks:
  elastic:
    driver: overlay 
